local kind       = {
  File          = "",
  Folder        = "",
  Array         = "󰅪",
  Boolean       = "󰨙",
  Class         = "",
  Codeium       = "󰘦",
  Color         = "",
  Constant      = "",
  Constructor   = "",
  Control       = "",
  Enum          = "",
  EnumMember    = "",
  Field         = "󰽐",
  Function      = "󰊕",
  Import        = "󰋺",
  Interface     = "",
  Key           = "󰌋",
  Keys          = "",
  Keyword       = "",
  Method        = "󰊕",
  Module        = "",
  Namespace     = "󰦮",
  Null          = "󰟢",
  Number        = "",
  Object        = "󰅩",
  Operator      = "󰆕",
  Package       = "",
  Property      = "",
  Copilot       = "",
  Reference     = "",
  Require       = "",
  Snippet       = "󱄽",
  Source        = "",
  Start         = "",
  String        = "",
  Struct        = "",
  Supermaven    = "",
  Tag           = "",
  Task          = "",
  Text          = "󱀍",
  TypeParameter = "󰗴",
  Unit          = "",
  Value         = "",
  Variable      = "󰫧",
}

local whitespace = {
  Tab       = "",
  Space     = "",
  Newline   = "",
  Nbsp      = "␣",
  Eob       = "",
  Fold      = "",
  FoldOpen  = "󰘖",
  FoldClose = "󰘕",
  FoldSep   = "│",
}

local ai         = {
  Copilot = "",
  ChatGPT = "",
  Anthropic = "",
  Bot = "󱙺",
}

local ui         = {
  File       = "",
  Folder     = "",
  FileTree   = "",
  Star       = "",
  Collapsed  = "",
  Expanded   = "",
  Dots       = "󰇘",
  Date       = "",
  Loaded     = "",
  NotLoaded  = "",
  Cmd        = "",
  Config     = "",
  Event      = "",
  Init       = "",
  Imports    = "󰋺",
  Keys       = "",
  Lazy       = "󰒲",
  Runtime    = "",
  Require    = "",
  Source     = "",
  Start      = "",
  Task       = "",
  Telescope  = "",
  Error      = "",
  Warning    = "",
  Info       = "",
  Hint       = "",
  Lock       = "",
  Unlock     = "󰿇",
  Plugin     = "",
  Breadcrumb = "»",
  Group      = "+",
  Debug      = "",
  Loading    = "",
  Done       = "",
  Web        = "",
  Todo       = "",
  Bug        = "",
  Note       = "",
  Doc        = "󱗖",
  Test       = "",
  Perf       = "",
  Hack       = "",
  Neovim     = "",
  Close      = "",
  Pin        = ""
}

local debug      = {
  CurrentFrame = '',
  Pause = '',
  Play = '',
  StepInto = '',
  StepOver = '',
  StepOut = '',
  StepBack = '',
  RunLast = '',
  Terminate = '',
  Disconnect = '',
}

local git        = {
  Added    = "",
  Modified = "",
  Removed  = "",
  Branch   = "",
  GitHub   = "",
}

local table      = {
  Bottom = '└',
  Middle = '├',
  Vertical = '│',
}

---@module 'Config.icon'
return {
  kind = vim.tbl_extend('force', kind, ai),
  whitespace = whitespace,
  ai = ai,
  ui = ui,
  debug = debug,
  git = git,
  table = table,
}
