---@class Config.Icons
local M      = {}

M.kind       = {
  File          = "",
  Folder        = "",
  Array         = "󰅪",
  Boolean       = "󰨙",
  Class         = "",
  Codeium       = "󰘦",
  Color         = "",
  Constant      = "",
  Constructor   = "",
  Control       = "",
  Enum          = "",
  EnumMember    = "",
  Field         = "󰽐",
  Function      = "󰊕",
  Import        = "󰋺",
  Interface     = "",
  Key           = "󰌋",
  Keys          = "",
  Keyword       = "",
  Method        = "󰊕",
  Module        = "",
  Namespace     = "󰦮",
  Null          = "󰟢",
  Number        = "",
  Object        = "󰅩",
  Operator      = "󰆕",
  Package       = "",
  Property      = "",
  Copilot       = "",
  Reference     = "",
  Require       = "",
  Snippet       = "󱄽",
  Source        = "",
  Start         = "",
  String        = "",
  Struct        = "",
  Supermaven    = "",
  Tag           = "",
  Task          = "",
  Text          = "󱀍",
  TypeParameter = "󰗴",
  Unit          = "",
  Value         = "",
  Variable      = "󰫧",
  Bot           = "󱙺",
  ChatGPT       = "",
  Anthropic     = "",
}

M.whitespace = {
  Tab       = "",
  Space     = "",
  Newline   = "",
  Nbsp      = "␣",
  Eob       = "",
  Fold      = "",
  FoldOpen  = "󰘖",
  FoldClose = "󰘕",
  FoldSep   = "│",
}

M.ui         = {
  File       = "",
  Folder     = "",
  FileTree   = "",
  Copilot    = "",
  TabNine    = "󰏚",
  Star       = "",
  Collapsed  = "",
  Expanded   = "",
  Dots       = "󰇘",
  Date       = "",
  Loaded     = "",
  NotLoaded  = "",
  Cmd        = "",
  Config     = "",
  Event      = "",
  Init       = "",
  Imports    = "󰋺",
  Keys       = "",
  Lazy       = "󰒲",
  Runtime    = "",
  Require    = "",
  Source     = "",
  Start      = "",
  Task       = "",
  Telescope  = "",
  Error      = "",
  Warning    = "",
  Info       = "",
  Hint       = "",
  Lock       = "",
  Unlock     = "󰿇",
  Plugin     = "",
  Breadcrumb = "»",
  Group      = "+",
  Debug      = "",
  Loading    = "",
  Done       = "",
  Web        = "",
}

M.debug      = {
  CurrentFrame = '',
  Pause = '',
  Play = '',
  StepInto = '',
  StepOver = '',
  StepOut = '',
  StepBack = '',
  RunLast = '',
  Terminate = '',
  Disconnect = '',
}

M.git        = {
  Added    = "",
  Modified = "",
  Removed  = "",
  Branch   = "",
  GitHub   = "",
}

return M
