return {
  name = 'cspell_ls',
  cmd = { 'cspell-lsp', '--stdio' },
  root_markers = {
    '.git',
    'cspell.json',
    '.cspell.json',
    'cspell.json',
    '.cSpell.json',
    'cSpell.json',
    'cspell.config.js',
    'cspell.config.cjs',
    'cspell.config.json',
    'cspell.config.yaml',
    'cspell.config.yml',
    'cspell.yaml',
    'cspell.yml',
  },
  filetypes = {
    'bash',
    'eelixir',
    'elixir',
    'go',
    'gohtml',
    'gohtmltmpl',
    'graphql',
    'javascript',
    'javascript.jsx',
    'javascriptreact',
    'jinja',
    'lua',
    'markdown',
    'mdx',
    'neorg',
    'opentofu',
    'php',
    'python',
    'rust',
    'sh',
    'terraform',
    'text',
    'toml',
    'twig',
    'typescript',
    'typescript.tsx',
    'typescriptreact',
    'yaml',
    'yaml.ansible',
    'zsh',
  },
}
