local M = {
  file = '󰈔',
  folder = '󰉋',
  folder_open = '󰝰',
  folder_empty = '󰉋',

  number = '',
  boolean = '󰨙',
  string = '',
  array = '󰅪',
  object = '󰅩',
  key = '',
  null = '',
  enum_member = '',
  struct = '',
  event = '',
  operator = '',
  type_parameter = '󰗴',
  component = '󰘦',
  fragment = '󰘦',
  type_alias = '󰰦',
  parameter = '',
  static_method = '󰡱',
  macro = '',
}